export const STORE_USER_DATA = 'STORE_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA ';


export const OPEN_PROFILE_MODAL = 'OPEN_PROFILE_MODAL';
export const CLOSE_PROFILE_MODAL = 'CLOSE_PROFILE_MODAL';

export const OPEN_NOTIFICATION_MODAL = 'OPEN_NOTIFICATION_MODAL';
export const CLOSE_NOTIFICATION_MODAL = 'CLOSE_NOTIFICATION_MODAL';

export const FETCHED_ALL_RECIPE_TO_STATE = 'FETCHED_ALL_RECIPE_TO_STATE';
export const FETCHED_SINGLE_RECIPE_TO_STATE = 'FETCHED_SINGLE_RECIPE_TO_STATE';
export const CLEAN_SINGLE_RECIPE = 'CLEAN_SINGLE_RECIPE';
export const REMOVE_RECIPE_TO_STATE = 'REMOVE_RECIPE_TO_STATE';
