export const STORE_USER_DATA = 'STORE_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA ';

export const FETCHED_USERS_TO_STATE = 'FETCHED_USERS_TO_STATE';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';
export const CLEAN_SINGLE_USER = 'CLEAN_SINGLE_USER';
export const FETCHED_USERS_SEARCHBAR = 'FETCHED_USERS_SEARCHBAR';

export const OPEN_PROFILE_MODAL = 'OPEN_PROFILE_MODAL';
export const CLOSE_PROFILE_MODAL = 'CLOSE_PROFILE_MODAL';

export const OPEN_NOTIFICATION_MODAL = 'OPEN_NOTIFICATION_MODAL';
export const CLOSE_NOTIFICATION_MODAL = 'CLOSE_NOTIFICATION_MODAL';

export const FETCHED_ALL_PROJECTS_TO_STATE = 'FETCHED_ALL_PROJECTS_TO_STATE';
export const FETCHED_SINGLE_PROJECT_TO_STATE = 'FETCHED_SINGLE_PROJECT_TO_STATE';
export const CLEAN_SINGLE_PROJECT = 'CLEAN_SINGLE_PROJECT'
